schema_version = "1.0.0"

id = "wxz_pie_menus"
version = "0.1.11"
name = "XZ-Blender作者预设"
tagline = "包含众多饼菜单和实用工具,启用预设前请备份好您的个人配置"
maintainer = "WXZ <wxz03111997@gmail.com>"
type = "add-on"
website = "https://github.com/xz-blender/wxz_pie_menus"
tags = ["3D View", "Modeling"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-2.0-or-later",
]
wheels = [ "wheels/requests-2.32.3-py3-none-any.whl"]